# Generated by Django 3.2.9 on 2021-12-01 20:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211201_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_alias',
            field=models.CharField(max_length=50, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_shorttext',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_status',
            field=models.BooleanField(null=True, verbose_name='Дата публикации новости'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
