# Generated by Django 3.2.9 on 2021-12-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211201_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_alias',
            field=models.CharField(max_length=50, unique=True, verbose_name='Псевдоним'),
        ),
    ]
