# Generated by Django 3.2.9 on 2021-12-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_comment_author_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
